template_extension: jst
template_function: _.template
# embed_assets: on


javascripts:
  html:
    - public/javascripts/jquery.js
    - public/javascripts/underscore.js
    - public/javascripts/geo.js
    - public/javascripts/modernizr.js
  mobile:
    - public/javascripts/jquery.js
    - public/javascripts/application.mobile.js
    - public/javascripts/jquery.mobile.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/geo.js
    - public/javascripts/console.js
    - public/javascripts/modernizr.js
    
  mobile-templates:
    - app/views/**/*.jst
    

stylesheets:
  html:
    - public/stylesheets/reset.css
    - public/stylesheets/stylesheet.css
  mobile:
    - public/stylesheets/jquery.mobile.css
    
